// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
)

type Conta struct {
	ID       int64     `json:"id"`
	Dono     string    `json:"dono"`
	Saldo    int64     `json:"saldo"`
	Moeda    string    `json:"moeda"`
	CriadaEm time.Time `json:"criada_em"`
}

type Mudanca struct {
	ID      int64 `json:"id"`
	IDConta int64 `json:"id_conta"`
	// esse valor pode ser negativo ou positivo
	Quantia  int64     `json:"quantia"`
	CriadaEm time.Time `json:"criada_em"`
}

type Seco struct {
	ID           uuid.UUID `json:"id"`
	NomeUsuario  string    `json:"nome_usuario"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiraEm     time.Time `json:"expira_em"`
	CriadaEm     time.Time `json:"criada_em"`
}

type Transferencia struct {
	ID          int64 `json:"id"`
	DeIDConta   int64 `json:"de_id_conta"`
	ParaIDConta int64 `json:"para_id_conta"`
	// esse valor so pode ser positivo
	Quantia  int64     `json:"quantia"`
	CriadaEm time.Time `json:"criada_em"`
}

type Usuario struct {
	NomeUsuario  string    `json:"nome_usuario"`
	SenhaHash    string    `json:"senha_hash"`
	NomeCompleto string    `json:"nome_completo"`
	Email        string    `json:"email"`
	MudancaSenha time.Time `json:"mudanca_senha"`
	CriadaEm     time.Time `json:"criada_em"`
}
